name: webtrit_phone_tools
description: WebTrit Phone CLI tools
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  path: ^1.9.1
  pub_updater: ^0.5.0
  mustache_template: ^2.0.2
  http: ^1.6.0
  archive: ^4.0.7
  yaml: ^3.1.3
  data:
    path: ../webtrit_phone_configurator/packages/data
  webtrit_appearance_theme:
    path: ../webtrit_phone/packages/webtrit_appearance_theme


dev_dependencies:
  build_runner: ^2.7.1
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.25.15
  webtrit_analysis:
    git: https://github.com/WebTrit/webtrit_analysis.git
  logging: ^1.3.0
  logging_appenders: ^1.4.0+1

executables:
  webtrit_phone_tools:
